name: Laravel
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_HOST: localhost
      DB_DATABASE: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '7700:7700'
    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          check-latest: true
      - name: Install NPM dependencies
        run: npm install
      - name: Compile assets for production
        run: npm run production
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Lint
        run: ./vendor/bin/phpcs
      - name: Migrate
        run: |
          php artisan migrate:fresh --seed
          php artisan migrate:refresh --seed
      - name: Test
        run: php artisan test
